/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziroom_grayscale_patch_DiffPatch */

#ifndef _Included_com_ziroom_grayscale_patch_DiffPatch
#define _Included_com_ziroom_grayscale_patch_DiffPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziroom_grayscale_patch_DiffPatch
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ziroom_grayscale_patch_DiffPatch_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ziroom_grayscale_patch_DiffPatch
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ziroom_grayscale_patch_DiffPatch_bsdiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
